server:
  port: 8083
spring:
  application:
    name: "reportes"
  devtools:
    add-properties: false
  webflux:
    base-path: "/api"
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
aws:
  dynamodb:
    endpoint: "http://localhost:8000"
entrypoint:
  sqs:
    region: "us-east-2"
    endpoint: "https://sqs.us-east-2.amazonaws.com"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/096212910572/Respuesta"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
