server:
  port: 8083
spring:
  application:
    name: "reportes"
  devtools:
    add-properties: false
  webflux:
    base-path: "/api"
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: "${SPRING_PROFILE:local}"
aws:
  dynamodb:
    endpoint: "${DYNAMO_DB_ENDPOINT:http://localhost:8000}"
  region: "${DYNAMO_DB_REGION:us-east-2}"
entrypoint:
  sqs:
    region: "${SQS_REGION:us-east-2}"
    endpoint: "${SQS_ENDPOINT:https://sqs.us-east-2.amazonaws.com}"
    queueUrl: "${SQS_LISTENER_RESPUESTA_ENDPOINT:https://sqs.us-east-2.amazonaws.com/096212910572/Respuesta}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

security:
  jwt:
    secretkey: "${JWT_SECRET_KEY:Bardelhaus1234567890Bardelhaus1234567890$}"

